### PR TITLE
Replaces rubocop with standard opinionated configuration

### PR DESCRIPTION
**Pull request by pftg**

### CODE REVIEW

**Comment by pftg** [comment]
@donv please check this. By adding standard there is no need to support `.rubocop.yml`

**Comment by donv** [comment]
I'll take a look.

**Comment by donv** [comment]
I am uncertain of the benefits.  We still have to maintain .standard.yml instead of .rubocop.yml.

I have use rubocop a lot, and I am willing to try out standards to gain a better perspective.

Can you rebase the PR?

**Comment by pftg** [comment]
@donv will do this after 5th oct

**Comment by pftg** [comment]
@donv updated PR please recheck it

**Comment by donv** [comment]
Good, but a couple of new conflicts crept inn with the other PRs.  Please rebase again.

**Comment by pftg** [comment]
@donv done

**Comment by pftg** [comment]
@donv please check this PR

**Comment by donv** [comment]
@pftg After the previous merge, you need to rebase this PR.  I am ready to merge when you rebase.

**Comment by pftg** [comment]
@donv  please merge this before other PR

**Comment by donv** [comment]
OK.  Let the experiment begin!

**Pull request merged**
