### PR TITLE
Prevents browser leaking while takes screenshots

### PR DESCRIPTION
**Pull request by pftg**
While worked on my project found that there is a browser leaking problem. After research found that each time we try detect driver class we initialize driver, and drivers run driver instances with browser instances

### CODE REVIEW

**Comment by donv** [comment]
Hi @pftg !

Thanks for the PR!  Looking at it now.

**Comment by pftg** [comment]
@donv there is issue for JRUBY platform, I'm going to fix it today. But will be great to see your feedback about using gemfile

**Comment by donv** [comment]
@pftg The PR looks good in general.  I have a few wishes before merging.

Please remove the `Gemfile.lock` from the PR.  It should not be committed for gems.

I'll await your changes for JRuby before commenting more.

**Comment by pftg** [comment]
@donv checked Travis settings and tests. Please review

**Comment by pftg** [comment]
@donv what do you think about this PR? I already use it on my project and got good performance improvement.

**Comment by donv** [comment]
This looks good to me 😄

**Pull request merged**
