### PR TITLE
Drops puma dependency

### PR DESCRIPTION
**Pull request by pftg**

### CODE REVIEW

**Comment by pftg** [comment]
@donv hey, capybara does not support puma 6, I disabled it for now

**Comment by donv** [comment]
I think we can wait it out:  https://github.com/teamcapybara/capybara/issues/2590

Seems they are on it.

**Comment by donv** [comment]
OK by me.  Ensure tests are passing in CI before merging.

**Comment by pftg** [comment]
@donv , hm webrick has been extracted from capybara as well ;( so let's await for puma support

**Pull request closed without merging**
