### PR TITLE
Adds 6 1 rails to test

### PR DESCRIPTION
**Pull request by pftg**

### CODE REVIEW

**Comment by pftg** [comment]
@donv please check this should fix problems with CI

**Comment by pftg** [comment]
Hm still some problems, will check today

**Comment by donv** [comment]
@pftg Looks like some checks are still failing?

**Comment by pftg** [comment]
@donv yep there is problem with rails 6.1 and chrome browser leak problem. Will check it later today

**Comment by pftg** [comment]
@donv I finally found what cause issues:

1. Used default bundler `Gemfile` for matrix tests
2. Several capybara drivers broke leak tests
3. On some instances there were slow requests: added more timeouts for it
4. And caret problem: added more time to make sure we have a stable screenshot.

Added fixes

**Pull request merged**
