### PR TITLE
Introduce VIP adapter for faster comparison

### PR DESCRIPTION
**Pull request by pftg**
Closes: donv/capybara-screenshot-diff#15

### CODE REVIEW

**Comment by pftg** [comment]
@donv please check the basic version to enable VIPS driver

**Comment by donv** [comment]
Hi @pftg !

Is this ready now?  It is a big PR with a lot of non-related changes.  Tests are green, and I am OK with merging if you are ready.

**Comment by donv** [comment]
@pftg Could you add a bit to the README to guide users on choosing a driver?

**Comment by pftg** [comment]
@donv added README updates

**Comment by donv** [comment]
Would be nice to get TruffleRuby working again, but I'll merge.

**Comment by pftg** [comment]
@donv great, thanks!

**Pull request merged**
