### PR TITLE
WIP: Fixes truffle build

### PR DESCRIPTION
**Pull request by pftg**

### CODE REVIEW

**Comment by donv** [comment]
@pftg Work in progress?

**Comment by pftg** [comment]
@donv yep, added fix on ruby-vips, will test it

**Comment by donv** [comment]
@pftg  Rebase and complete this PR?

**Comment by pftg** [comment]
@donv I need to fix ruby-vips first, to support truffelruby, for now it's not working there. Only jruby. I have not found time to fix ruby-vips yet

**Comment by pftg** [comment]
But maybe we can run tests for chunky_png at least, will think about it

**Comment by donv** [comment]
Yes, runking with chunky_png would be enough for now.

**Pull request closed without merging**
