### PR TITLE
Do not use ~ on save images + use reference/current tag + README fixes

### PR DESCRIPTION
**Pull request by hackhowtofaq**
* Fix in README

### CODE REVIEW

**Comment by donv** [comment]
Hi @hackhowtofaq !

Thanks for the PR.  I'd like to discuss the change with you a bit.

The `~` at the end was added to avoid checking the file into VCS since it matches a common ignore pattern: emacs backup file.  I still think this is a good idea.  Do you have another view?

The "0" and "1" were added since they are short and sort correctly as "before" and "after".  "reference" and "current" are more explanatory, but they are also longer and sort in the opposite order.  If this is important to you, I'll consider it.  Do you use capybara-screenshot-diff?

**Comment by donv** [comment]
The README change is great!

**Comment by donv** [comment]
> Hello @donv and thank you for this great gem!
> 
> I have just started using it.
> 
> > The `~` at the end was added to avoid checking the file into VCS since it matches a common ignore pattern: emacs backup file. I still think this is a good idea. Do you have another view?
> 
> The `~` at the end makes the type of the file not recognizable, so it is not possible to open it with the default application (double click).

This is true. I have configured my IDE to get around this.

> > The "0" and "1" were added since they are short and sort correctly as "before" and "after". "reference" and "current" are more explanatory, but they are also longer and sort in the opposite order. If this is important to you, I'll consider it. Do you use capybara-screenshot-diff?
> 
> I don't want to add cognitive overhead and/or misinterpretation errors, thus I prefer the reference/current tagging.

What about "old" and "new" ?  Or "commited" for the reference?  I think I prefer "commited" for the reference.

I am starting to accept this change.

**Comment by hackhowtofaq** [comment]
Yeap, committed is ok for me!

**Comment by donv** [comment]
So change it to "committed" and maybe "new", and I'll merge it.

**Comment by hackhowtofaq** [comment]
Thank you.

**Comment by donv** [comment]
Thank you!  I have released version 1.3.1 with your change.

**Pull request merged**
