### PR TITLE
`ArgumentError: comparison of Float with nil failed` in `Screenshoter#wait_images_loaded`

### PR DESCRIPTION
**Pull request by pftg**
I'm getting the exception below intermittently when running my tests. The problem is at `screenshoter.rb:119` the `timeout` is `nil` because of this:

```ruby
# stable_screenshoter.rb:16 removing :wait from capture_options here
@screenshoter = Diff.screenshoter.new(capture_options.except(*STABILITY_OPTIONS), driver)
```

I think when I run locally `pending_image` is `nil` so the tests pass, but on CircleCI it's non-`nil` thus the intermittent failure. That is, `timeout` is never checked locally.

@pftg Should `wait` really be excluded from that `capture_options`?

```
     Failure/Error:
       screenshot "with_ocr_modal_open",
                  tolerance: success_alert_tolerance,
                  skip_area: skip_area
     
     ArgumentError:
       comparison of Float with nil failed
     
     [Screenshot Image]: /home/circleci/app/tmp/capybara/failures_r_spec_example_groups_the_new_admin_order_line_items_page_with_featurereceiptocr_enabled_shows_usable_ocr_data_179.png

     [Screenshot HTML]: /home/circleci/app/tmp/capybara/failures_r_spec_example_groups_the_new_admin_order_line_items_page_with_featurereceiptocr_enabled_shows_usable_ocr_data_179.html

     
     # ./*************/ruby/3.2.0/bundler/gems/capybara-screenshot-diff-116a7c52d529/lib/capybara/screenshot/diff/screenshoter.rb:119:in `>='
     # ./*************/ruby/3.2.0/bundler/gems/capybara-screenshot-diff-116a7c52d529/lib/capybara/screenshot/diff/screenshoter.rb:119:in `block in wait_images_loaded'
     # ./*************/ruby/3.2.0/bundler/gems/capybara-screenshot-diff-116a7c52d529/lib/capybara/screenshot/diff/screenshoter.rb:115:in `loop'
     # ./*************/ruby/3.2.0/bundler/gems/capybara-screenshot-diff-116a7c52d529/lib/capybara/screenshot/diff/screenshoter.rb:115:in `wait_images_loaded'
     # ./*************/ruby/3.2.0/bundler/gems/capybara-screenshot-diff-116a7c52d529/lib/capybara/screenshot/diff/screenshoter.rb:100:in `prepare_page_for_screenshot'
     # ./*************/ruby/3.2.0/bundler/gems/capybara-screenshot-diff-116a7c52d529/lib/capybara/screenshot/diff/screenshoter.rb:55:in `take_screenshot'
     # ./*************/ruby/3.2.0/bundler/gems/capybara-screenshot-diff-116a7c52d529/lib/capybara/screenshot/diff/stable_screenshoter.rb:53:in `block in take_stable_screenshot'
     # ./*************/ruby/3.2.0/bundler/gems/capybara-screenshot-diff-116a7c52d529/lib/capybara/screenshot/diff/stable_screenshoter.rb:44:in `step'
     # ./*************/ruby/3.2.0/bundler/gems/capybara-screenshot-diff-116a7c52d529/lib/capybara/screenshot/diff/stable_screenshoter.rb:44:in `take_stable_screenshot'
     # ./*************/ruby/3.2.0/bundler/gems/capybara-screenshot-diff-116a7c52d529/lib/capybara/screenshot/diff/stable_screenshoter.rb:23:in `take_comparison_screenshot'
     # ./*************/ruby/3.2.0/bundler/gems/capybara-screenshot-diff-116a7c52d529/lib/capybara/screenshot/diff/screenshot_matcher.rb:82:in `take_comparison_screenshot'
     # ./*************/ruby/3.2.0/bundler/gems/capybara-screenshot-diff-116a7c52d529/lib/capybara/screenshot/diff/screenshot_matcher.rb:54:in `build_screenshot_matches_job'
     # ./*************/ruby/3.2.0/bundler/gems/capybara-screenshot-diff-116a7c52d529/lib/capybara/screenshot/diff/****_methods.rb:119:in `build_screenshot_matches_job'
     # ./*************/ruby/3.2.0/bundler/gems/capybara-screenshot-diff-116a7c52d529/lib/capybara/screenshot/diff/****_methods.rb:73:in `screenshot'
     # ./spec/system/admin/orders/jp_line_items_page_spec.rb:554:in `block (3 levels) in <top (required)>'
```

### CODE REVIEW

**Comment by pftg** [comment]
@asavageiv please check

**Comment by asavageiv** [comment]
I _think_ this will work because `#take_stable_screenshot` will do the waiting at a higher level. If that's correct, this looks good to me.

**Comment by asavageiv** [comment]
I'm wondering why `stable_screenshoter_test.rb` didn't catch the error? I guess to test the path that failed we'd need to stub `BrowserHelpers.pending_image_to_load` to return something `falsey` and right now it's always returning something `truthy`.

**Comment by pftg** [comment]
> I'm wondering why stable_screenshoter_test.rb didn't catch the error?

@asavageiv thanks for notice, I checked it too and updated.

**Pull request merged**
