### PR TITLE
Adds ruby 3.0 support

### PR DESCRIPTION
**Pull request by pftg**

### CODE REVIEW

**Comment by donv** [comment]
@pftg No checks?

**Comment by pftg** [comment]
@donv yeh, will check it later. for now run checks on https://github.com/jetthoughts/capybara-screenshot-diff/pull/7

**Comment by pftg** [comment]
@donv please check tests from https://github.com/jetthoughts/capybara-screenshot-diff/pull/7

**Comment by pftg** [comment]
@donv added fix for CI

**Review by donv — APPROVED** [review]

**Comment by donv** [comment]
@pftg Released new version 1.5.0 with Ruby 3 support :). Thanks!

**Pull request merged**
